spring:
  application:
    name: fraud-detection-service

server:
  port: ${SERVER_PORT:8092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
